src/main.cpp File Reference
#include `Arduino.h`
#include `SPI.h`
#include <Wire.h>
#include `Adafruit_Keypad.h`
#include <TTP229.h>
#include `RF24.h`
#include `printf.h`
#include `DT500-MID.h`
#include <engine.h>
#include <wireless.h>
#include <debug.h>
Functions
void setup ()
void loop ()
Variables
wireless DH500_radio
debug DEBUG
int role = 0
int responding
Function Documentation
loop()
void loop ()
            {
  // put your main code here, to run repeatedly:
  DT500.lastDebounceTime = millis();
  DT500.loopCount++;
  DT500.get_count();
  DT500.error = DT500.push_buttons_joystick();
  DH500_radio.set_PayloadStruct();
  DH500_radio.Transmit();
  DEBUG.display_time_DEBUG();
}
References DEBUG, DH500_radio, debug::display_time_DEBUG(), DT500, engen::error, engen::get_count(), engen::lastDebounceTime, engen::loopCount, engen::push_buttons_joystick(), wireless::set_PayloadStruct(), and wireless::Transmit().
setup()
void setup ()
             {
  // put your setup code here, to run once:
    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, 255);
    // SSD1306_SWITCHCAPVCC = generate display voltage from 3.3V internally
    if (!display.begin(SSD1306_SWITCHCAPVCC, SCREEN_ADDRESS))
    {
        Serial.println(F("SSD1306 allocation failed"));
        for (;;)
            ; // Don't proceed, loop forever
    }
// Show initial display buffer contents on the screen --
// the library initializes this with an Adafruit splash screen.
    digitalWrite(LED_BUILTIN, 0);
    digitalWrite(LED_BUILTIN, 255);
    nrf24_setup();
    
    DH500_radio.int_PayloadStruct();
      
    DT500.Arduino_digital_analog_int();
    delay(500);
    // Clear the buffer
    display.clearDisplay();
    Serial.begin(9600);
}
References engen::Arduino_digital_analog_int(), DH500_radio, display(), DT500, wireless::int_PayloadStruct(), nrf24_setup(), and SCREEN_ADDRESS.
Variable Documentation
DEBUG
debug DEBUG
Referenced by loop().
DH500_radio
wireless DH500_radio
Referenced by loop(), and setup().
responding
int responding
role
int role = 0