.TH "include/DT500-Os.h" 3 "Thu Jan 6 2022" "Version 0.1" "arduino_train_controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/DT500-Os.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDrf\fP   = Duplex_RF;"
.br
.ti -1c
.RI "#define \fBIRm\fP   = IR_mode;"
.br
.ti -1c
.RI "#define \fBTid\fP   = Throt_ID;"
.br
.ti -1c
.RI "#define \fBXPs\fP   = XP Slots;"
.br
.ti -1c
.RI "#define \fBRPd\fP   = RPdn_20m;"
.br
.ti -1c
.RI "#define \fBXPf\fP   = XPFnHold;"
.br
.ti -1c
.RI "#define \fBNIS\fP   = noIDLSho;"
.br
.ti -1c
.RI "#define \fBCl\fP   = Clicks;"
.br
.ti -1c
.RI "#define \fBFcl\fP   = Fclock;"
.br
.ti -1c
.RI "#define \fBHR12\fP   = Clock_12Hr;"
.br
.ti -1c
.RI "#define \fBNB\fP   = NoBlstic;"
.br
.ti -1c
.RI "#define \fBST\fP   = STimeout;"
.br
.ti -1c
.RI "#define \fBFs\fP   = F3_Static;"
.br
.ti -1c
.RI "#define \fBFm\fP   = F2_Mom;"
.br
.ti -1c
.RI "#define \fBFa\fP   = F2_Analog;"
.br
.ti -1c
.RI "#define \fBMSG\fP   = MsgFilter;"
.br
.ti -1c
.RI "#define \fBSLF\fP   = SLFollow;"
.br
.ti -1c
.RI "#define \fBESI\fP   = ES_Idle;"
.br
.ti -1c
.RI "#define \fBPRS\fP   = PWRSaver;"
.br
.ti -1c
.RI "#define \fBIR\fP   = IRRelease;"
.br
.ti -1c
.RI "#define \fBDp\fP   = DplxBad;"
.br
.ti -1c
.RI "#define \fBDXR\fP   = DxRxLPwr;"
.br
.ti -1c
.RI "#define \fBNT\fP   = NewTypes;"
.br
.ti -1c
.RI "#define \fBNUT\fP   = Nu_Type_;"
.br
.ti -1c
.RI "#define \fBRec\fP   = Recall_ #;"
.br
.ti -1c
.RI "#define \fBBl\fP   = BackLite;"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Bl   = BackLite;"

.SS "#define Cl   = Clicks;"

.SS "#define Dp   = DplxBad;"

.SS "#define Drf   = Duplex_RF;"

.SS "#define DXR   = DxRxLPwr;"

.SS "#define ESI   = ES_Idle;"

.SS "#define Fa   = F2_Analog;"

.SS "#define Fcl   = Fclock;"

.SS "#define Fm   = F2_Mom;"

.SS "#define Fs   = F3_Static;"

.SS "#define HR12   = Clock_12Hr;"

.SS "#define IR   = IRRelease;"

.SS "#define IRm   = IR_mode;"

.SS "#define MSG   = MsgFilter;"

.SS "#define NB   = NoBlstic;"

.SS "#define NIS   = noIDLSho;"

.SS "#define NT   = NewTypes;"

.SS "#define NUT   = Nu_Type_;"

.SS "#define PRS   = PWRSaver;"

.SS "#define Rec   = Recall_ #;"

.SS "#define RPd   = RPdn_20m;"

.SS "#define SLF   = SLFollow;"

.SS "#define ST   = STimeout;"

.SS "#define Tid   = Throt_ID;"

.SS "#define XPf   = XPFnHold;"

.SS "#define XPs   = XP Slots;"

.SH "Author"
.PP 
Generated automatically by Doxygen for arduino_train_controller from the source code\&.
