.TH "include/DT500-MID.h" 3 "Thu Jan 6 2022" "Version 0.1" "arduino_train_controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/DT500-MID.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFn\fP   'Function'"
.br
.ti -1c
.RI "#define \fBLo\fP   'Loco_Selection'"
.br
.ti -1c
.RI "#define \fBMu\fP   'MU'"
.br
.ti -1c
.RI "#define \fBSw\fP   'Switch'"
.br
.ti -1c
.RI "#define \fBPw\fP   'Power'"
.br
.ti -1c
.RI "#define \fBSe\fP   'Status_Edit'"
.br
.ti -1c
.RI "#define \fBPg\fP   'Programming_Paged'"
.br
.ti -1c
.RI "#define \fBPh\fP   'Programming_Physical'"
.br
.ti -1c
.RI "#define \fBPd\fP   'Programming_Direct'"
.br
.ti -1c
.RI "#define \fBPo\fP   'Programming_Operations_Mode'"
.br
.ti -1c
.RI "#define \fBRe\fP   'Recall'"
.br
.ti -1c
.RI "#define \fBFd\fP   'Find'"
.br
.ti -1c
.RI "#define \fBEc\fP   'Edit_clock'"
.br
.ti -1c
.RI "#define \fBEf\fP   'Edit_clock_rate'"
.br
.ti -1c
.RI "#define \fBEa\fP   'Edit_alarm'"
.br
.ti -1c
.RI "#define \fBEr\fP   'Edit_routes'"
.br
.ti -1c
.RI "#define \fBErr\fP   'error'"
.br
.ti -1c
.RI "#define \fBE1\fP   'Change_LocoNet_ID'"
.br
.ti -1c
.RI "#define \fBEQem\fP   'Other_edit_modes'"
.br
.ti -1c
.RI "#define \fBQur\fP   'Query'"
.br
.ti -1c
.RI "#define \fBIn\fP   'Input'"
.br
.ti -1c
.RI "#define \fBTRPOIN\fP   'Track_Power_Indicator'"
.br
.ti -1c
.RI "#define \fBmoter\fP   0"
.br
.ti -1c
.RI "#define \fBFn_code\fP   1"
.br
.ti -1c
.RI "#define \fBLo_code\fP   2"
.br
.ti -1c
.RI "#define \fBMu_code\fP   3"
.br
.ti -1c
.RI "#define \fBSw_code\fP   4"
.br
.ti -1c
.RI "#define \fBPw_code\fP   5"
.br
.ti -1c
.RI "#define \fBSe_code\fP   6"
.br
.ti -1c
.RI "#define \fBPg_code\fP   7"
.br
.ti -1c
.RI "#define \fBPh_code\fP   8"
.br
.ti -1c
.RI "#define \fBPd_code\fP   9"
.br
.ti -1c
.RI "#define \fBPo_code\fP   10"
.br
.ti -1c
.RI "#define \fBRe_code\fP   11"
.br
.ti -1c
.RI "#define \fBFd_code\fP   12"
.br
.ti -1c
.RI "#define \fBEc_code\fP   13"
.br
.ti -1c
.RI "#define \fBEf_code\fP   14"
.br
.ti -1c
.RI "#define \fBEa_code\fP   15"
.br
.ti -1c
.RI "#define \fBEr_code\fP   16"
.br
.ti -1c
.RI "#define \fBErr_code\fP   17"
.br
.ti -1c
.RI "#define \fBE1_code\fP   18"
.br
.ti -1c
.RI "#define \fBEQem_code\fP   19"
.br
.ti -1c
.RI "#define \fBQur_code\fP   20"
.br
.ti -1c
.RI "#define \fBIn_code\fP   21"
.br
.ti -1c
.RI "#define \fBTRPOIN_code\fP   22"
.br
.ti -1c
.RI "#define \fBtest_moter\fP   300"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define E1   'Change_LocoNet_ID'"

.SS "#define E1_code   18"

.SS "#define Ea   'Edit_alarm'"

.SS "#define Ea_code   15"

.SS "#define Ec   'Edit_clock'"

.SS "#define Ec_code   13"

.SS "#define Ef   'Edit_clock_rate'"

.SS "#define Ef_code   14"

.SS "#define EQem   'Other_edit_modes'"

.SS "#define EQem_code   19"

.SS "#define Er   'Edit_routes'"

.SS "#define Er_code   16"

.SS "#define Err   'error'"

.SS "#define Err_code   17"

.SS "#define Fd   'Find'"

.SS "#define Fd_code   12"

.SS "#define Fn   'Function'"

.SS "#define Fn_code   1"

.SS "#define In   'Input'"

.SS "#define In_code   21"

.SS "#define Lo   'Loco_Selection'"

.SS "#define Lo_code   2"

.SS "#define moter   0"

.SS "#define Mu   'MU'"

.SS "#define Mu_code   3"

.SS "#define Pd   'Programming_Direct'"

.SS "#define Pd_code   9"

.SS "#define Pg   'Programming_Paged'"

.SS "#define Pg_code   7"

.SS "#define Ph   'Programming_Physical'"

.SS "#define Ph_code   8"

.SS "#define Po   'Programming_Operations_Mode'"

.SS "#define Po_code   10"

.SS "#define Pw   'Power'"

.SS "#define Pw_code   5"

.SS "#define Qur   'Query'"

.SS "#define Qur_code   20"

.SS "#define Re   'Recall'"

.SS "#define Re_code   11"

.SS "#define Se   'Status_Edit'"

.SS "#define Se_code   6"

.SS "#define Sw   'Switch'"

.SS "#define Sw_code   4"

.SS "#define test_moter   300"

.SS "#define TRPOIN   'Track_Power_Indicator'"

.SS "#define TRPOIN_code   22"

.SH "Author"
.PP 
Generated automatically by Doxygen for arduino_train_controller from the source code\&.
