.TH "include/Interpolation_math.h" 3 "Thu Jan 6 2022" "Version 0.1" "arduino_train_controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Interpolation_math.h
.SH SYNOPSIS
.br
.PP
\fC#include 'WProgram\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBInterpolation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arduino_train_controller from the source code\&.
