.TH "include/notuesd.h" 3 "Thu Jan 6 2022" "Version 0.1" "arduino_train_controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/notuesd.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnrf24_setup\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int nrf24_setup ()"

.PP
.nf
2  {
3 
4      Serial\&.println(F("\n\rRF24/examples/scanner/"));
5 
6      //
7      // Setup and configure rf radio
8      //
9      if (!radio\&.begin())
10      {
11          Serial\&.println(F(""));
12          Serial\&.println(F("radio hardware is not responding!!"));
13          Serial\&.println(F(""));
14          return 3;
15      }
16      radio\&.setAutoAck(false);
17 
18      // Get into standby mode
19      radio\&.startListening();
20      radio\&.stopListening();
21      radio\&.printDetails();
22 
23      // Print out header, high then low digit
24      int i = 0;
25      while (i < num_channels)
26      {
27          Serial\&.print(i >> 4, HEX);
28         ++i;
29      }
30      Serial\&.println();
31      i = 0;
32      while (i < num_channels)
33      {
34          Serial\&.print(i & 0xf, HEX);
35          ++i;
36       }
37      Serial\&.println();
38      //delay(1000);
39 
40  return 1;
41  }
.fi
.PP
References \fBnum_channels\fP, and \fBradio()\fP\&.
.PP
Referenced by \fBsetup()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for arduino_train_controller from the source code\&.
