.TH "PayloadStruct" 3 "Thu Jan 6 2022" "Version 0.1" "arduino_train_controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PayloadStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wireless\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBAddress\fP"
.br
.ti -1c
.RI "unsigned long \fBpayloadID\fP"
.br
.ti -1c
.RI "int \fBb4_Address\fP"
.br
.ti -1c
.RI "int \fBcv\fP"
.br
.ti -1c
.RI "int \fBR_W\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.ti -1c
.RI "int \fBdata\fP"
.br
.ti -1c
.RI "bool \fBconnected\fP"
.br
.ti -1c
.RI "bool \fBdisconet\fP"
.br
.ti -1c
.RI "int \fBC_L_T\fP"
.br
.ti -1c
.RI "int \fBC_R_T\fP"
.br
.ti -1c
.RI "int \fBC_R_K\fP"
.br
.ti -1c
.RI "int \fBC_L_T_A\fP"
.br
.ti -1c
.RI "int \fBC_R_T_A\fP"
.br
.ti -1c
.RI "int \fBC_S\fP"
.br
.ti -1c
.RI "int \fBC_P\fP"
.br
.ti -1c
.RI "int \fBmoters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "unsigned long PayloadStruct::Address"

.PP
Referenced by \fBwireless::brodcast()\fP, \fBwireless::int_PayloadStruct()\fP, \fBwireless::recieved()\fP, and \fBwireless::Transmit()\fP\&.
.SS "int PayloadStruct::b"

.PP
Referenced by \fBwireless::brodcast()\fP\&.
.SS "int PayloadStruct::b4_Address"

.PP
Referenced by \fBwireless::int_PayloadStruct()\fP\&.
.SS "int PayloadStruct::C_L_T"

.PP
Referenced by \fBwireless::int_PayloadStruct()\fP, and \fBwireless::set_PayloadStruct()\fP\&.
.SS "int PayloadStruct::C_L_T_A"

.SS "int PayloadStruct::C_P"

.SS "int PayloadStruct::C_R_K"

.SS "int PayloadStruct::C_R_T"

.SS "int PayloadStruct::C_R_T_A"

.SS "int PayloadStruct::C_S"

.SS "bool PayloadStruct::connected"

.SS "int PayloadStruct::cv"

.SS "int PayloadStruct::data"

.SS "bool PayloadStruct::disconet"

.SS "int PayloadStruct::moters"

.SS "unsigned long PayloadStruct::payloadID"

.PP
Referenced by \fBwireless::brodcast()\fP, \fBwireless::recieved()\fP, and \fBwireless::Transmit()\fP\&.
.SS "int PayloadStruct::R_W"


.SH "Author"
.PP 
Generated automatically by Doxygen for arduino_train_controller from the source code\&.
