wireless Class Reference
#include <wireless.h>
Public Member Functions
int recieved ()
int setup ()
int brodcast ()
int Transmit ()
int set_PayloadStruct ()
int int_PayloadStruct ()
Data Fields
int role = 0
int responding
Private Attributes
unsigned long previousMillis1 = 0
unsigned long interval1 = 10000
unsigned long previousMillis2 = 0
unsigned long interval2 = 5000
Detailed Description
Member Function Documentation
brodcast()
int wireless::brodcast ()
{
    unsigned long currentMillis = millis();
    // unsigned long currentMillis3 = millis();
    // int report2 = 0;
    bool report;
    TX_RX_BC.b = 1;
    if (currentMillis - previousMillis1 > interval1)
    {
        radio.stopListening(); // put radio in TX mode
        radio.openWritingPipe(TX_RX_BC.Address);
        // According to the datasheet, the auto-retry features's delay value should
        // be "skewed" to allow the RX node to receive 1 transmission at a time.
        // So, use varying delay between retry attempts and 15 (at most) retry attempts
        radio.setRetries(((role * 3) % 12) + 3, 15); // maximum value is 15 for both args
        previousMillis1 = currentMillis; // save the last time I blinked the LED
        unsigned long start_timer = micros(); // start the timer
        report = radio.write(&TX_RX_BC, sizeof(TX_RX_BC)); // transmit & save the report
        unsigned long end_timer = micros(); // end the timer
        if (report)
        {
            // payload was delivered
            Serial.print(F("Transmission of payloadID "));
            Serial.print(TX_RX_BC.payloadID); // print payloadID
            Serial.print(F(" as Address "));
            Serial.print(TX_RX_BC.Address); // print nodeID
            Serial.print(F(" successful!"));
            Serial.print(F(" Time to transmit: "));
            Serial.print(end_timer - start_timer); // print the timer result
            Serial.println(F(" us"));
        }
        else
        {
            Serial.println(F("Transmission failed or timed out")); // payload was not delivered
        }
        TX_RX_BC.payloadID++; // increment payload number
    }
    currentMillis = millis();
    return report;
}
References PayloadStruct::Address, PayloadStruct::b, interval1, PayloadStruct::payloadID, previousMillis1, radio(), role, and TX_RX_BC.
int_PayloadStruct()
int wireless::int_PayloadStruct ()
{
    TX_RX_BC.C_L_T = DT500.analog_joystick_x;
    TX_RX_BC.Address = b2_Digi_Decoder_Address;
    TX_RX_BC.b4_Address = b4_Digi_ADD_L + b4_Digi_Address_H ;
    return 1;
}
References PayloadStruct::Address, engen::analog_joystick_x, b2_Digi_Decoder_Address, PayloadStruct::b4_Address, b4_Digi_ADD_L, b4_Digi_Address_H, PayloadStruct::C_L_T, DT500, and TX_RX_BC.
Referenced by setup().
recieved()
int wireless::recieved ()
{
    unsigned long currentMillis3 = millis();
    if (currentMillis3 - previousMillis2 > interval2)
    {
        previousMillis2 = currentMillis3; // save the last time I blinked the LED
        Serial.print(F("RX "));
        for (uint8_t i = 0; i < 5; ++i)
            radio.openReadingPipe(i, DT500.RX_ADD);
        radio.startListening(); // put radio in RX mode // end the timer
        Serial.print(F("RX? "));
        uint8_t pipe;
        if (radio.available(&pipe))
        { // is there a payload? get the pipe number that recieved it
            uint8_t bytes = radio.getPayloadSize(); // get the size of the payload
            radio.read(&TX_RX_BC, bytes); // fetch payload from FIFO
            Serial.print(F("Received "));
            Serial.print(bytes); // print the size of the payload
            Serial.print(F(" bytes on pipe "));
            Serial.print(pipe); // print the pipe number
            Serial.print(F(" from node "));
            Serial.print(TX_RX_BC.Address); // print the payload's origin
            Serial.print(F(". PayloadID: "));
            Serial.println(TX_RX_BC.payloadID); // print the payload's number
        }
    }
    currentMillis3 = millis();
    return 0;
}
References PayloadStruct::Address, DT500, interval2, PayloadStruct::payloadID, previousMillis2, radio(), engen::RX_ADD, and TX_RX_BC.
set_PayloadStruct()
int wireless::set_PayloadStruct ()
{
   TX_RX_BC.C_L_T = DT500.analog_joystick_x;
   return 1;
}
References engen::analog_joystick_x, PayloadStruct::C_L_T, DT500, and TX_RX_BC.
Referenced by loop().
setup()
int wireless::setup ()
{
    bool report;
    report = nrf24_setup();
    return report;
}
References nrf24_setup().
Transmit()
int wireless::Transmit ()
{
    unsigned long currentMillis = millis();
    bool report;
    if (currentMillis - previousMillis1 > interval1)
    {
        radio.stopListening(); // put radio in TX mode
        radio.openWritingPipe(TX_RX_BC.Address);
        // According to the datasheet, the auto-retry features's delay value should
        // be "skewed" to allow the RX node to receive 1 transmission at a time.
        // So, use varying delay between retry attempts and 15 (at most) retry attempts
        radio.setRetries(((role * 3) % 12) + 3, 15); // maximum value is 15 for both args
        previousMillis1 = currentMillis; // save the last time I blinked the LED
        unsigned long start_timer = micros(); // start the timer
        report = radio.write(&TX_RX_BC, sizeof(TX_RX_BC)); // transmit & save the report
        unsigned long end_timer = micros(); // end the timer
        if (report)
        {
            // payload was delivered
            Serial.print(F("Transmission of payloadID "));
            Serial.print(TX_RX_BC.payloadID); // print payloadID
            Serial.print(F(" as Address "));
            Serial.print(TX_RX_BC.Address); // print nodeID
            Serial.print(F(" successful!"));
            Serial.print(F(" Time to transmit: "));
            Serial.print(end_timer - start_timer); // print the timer result
            Serial.println(F(" us"));
        }
        else
        {
            Serial.println(F("Transmission failed or timed out")); // payload was not delivered
        }
        TX_RX_BC.payloadID++; // increment payload number
    }
    currentMillis = millis();
    return report;
}
References PayloadStruct::Address, interval1, PayloadStruct::payloadID, previousMillis1, radio(), role, and TX_RX_BC.
Referenced by loop().
Field Documentation
interval1
unsigned long wireless::interval1 = 10000 [private]
Referenced by brodcast(), and Transmit().
interval2
unsigned long wireless::interval2 = 5000 [private]
Referenced by recieved().
previousMillis1
unsigned long wireless::previousMillis1 = 0 [private]
Referenced by brodcast(), and Transmit().
previousMillis2
unsigned long wireless::previousMillis2 = 0 [private]
Referenced by recieved().
responding
int wireless::responding
role
int wireless::role = 0
Referenced by brodcast(), and Transmit().
The documentation for this class was generated from the following file:
include/wireless.h