//DT500 Option Screen
#define Drf = Duplex_RF;   // On enables RF24 to operate in Duplex mode. Off turns off Duplex choice
#define IRm = IR_mode;     // On enables IR mode when disconnected and IR receiver detected on LocoNet
#define Tid = Throt_ID;    // Optional unique throttle ID
#define XPs = XP Slots;    // Enable or disabel the use of Expanded slots when available
#define RPd = RPdn_20m;    // On enables throttle to power off after being in power save for 20 minutes
#define XPf = XPFnHold;    // On allows multiple expanded function keys per X1 or X2 choice
#define NIS = noIDLSho;    // Off allows “Idle” to flash in right hand loco address area when system is Idle
#define Cl = Clicks;       // On enables clicking when making any keypad or knob changes
#define Fcl = Fclock;      // On enables Fast Clock in center display
#define HR12 = Clock_12Hr; // On selects 12Hr vs 24Hr clock display mode
#define NB = NoBlstic;     // Off enables ballstic tracking by proving ratesensitive knop steps so faster turning gives bigger step changes
#define ST = STimeout;     // On shortens the amoutn of time before the throttle kicks into Power Save when no changes have taken place
#define Fs = F3_Static;    // On makes F3 key On/Off action
#define Fm = F2_Mom;       // On makes F2 key momentary action, used for playable whistle where available
#define Fa = F2_Analog;    // On enables optional F2 key pressure-sensitive analog mode
#define MSG = MsgFilter;   // On stops throttle messages from displaying when selecting locomotives
#define SLF = SLFollow;    // On enables slot following mode for locomotives selected in multiple throttles
#define ESI = ES_Idle;     // On freezes all locomotives when Emerg-Stop key pressed. Off stops only locomotive selected in throttle
#define PRS = PWRSaver;    // On enables Radio?IR mode power save on throttle inactivity
#define IR = IRRelease;    // On allows IR/Simplez Radio throttles to release loco addresses when unplugged
#define Dp = DplxBad;      // On enables white flashlight LED to blink when repeted Duplex radio messages fail
#define DXR = DxRxLPwr;    // On enables maximum Duplex power saviing, disables continuous update of slot following
#define NT = NewTypes;     // On allows throttle to overide command station new- type loco speed step settings
#define NUT = Nu_Type_;    // 128 speed step---setting 14 speed step setting---reserved 28 speed step setting---Advanced 128 speed step setting reserved---Advanced 28 speed step setting
#define Rec = Recall_ #;   // Recall stack set at last 4 entries---Recall stack set at least 8 entries---Recall stack set at last 16 entries
#define Bl = BackLite;     // Maximum backlight brightness---Maximum backlight brightness - lowest power usage
#define FD = FactoryD;     // Select on and press enter key to force all options settings to factory defaults